"""B87-I3 governed memory contracts and shared kernel."""

from .contracts import (
    APPROVAL_TRANSITIONS,
    ELIGIBILITY_REASON_ORDER,
    GOVERNED_RELATIONSHIP_TYPES,
    LIFECYCLE_TRANSITIONS,
    MEMORY_APPROVAL_AUTHORITY_CLASSES,
    MEMORY_APPROVAL_OPERATION,
    MEMORY_DOMAINS,
    MEMORY_RECORD_TYPES,
    MEMORY_RELATIONSHIP_OPERATION,
    NOLAN_INCLUSIVE_AUTHORITY_CLASSES,
    RELATIONSHIP_TYPES,
    EligibilityContext,
    EligibilityDecision,
    MemoryApprovalGrant,
    MemoryRelationshipGrant,
    RecordRelationship,
    approval_authority_classes_for,
    memory_domain_for,
    validate_approval_transition,
    validate_lifecycle_transition,
)
from .construct_contracts import (
    CONSTRUCT_PAYLOAD_TABLES,
    CONSTRUCT_PAYLOAD_TYPES,
    CONSTRUCT_RELATIONSHIP_POLICIES,
    ArchitectureDecisionPayload,
    ConstructDoctrinePayload,
    ConstructEntityPayload,
    ConstructRelationshipPayload,
    PreferenceRecordPayload,
    ProjectStatePayload,
    TerminologyDefinitionPayload,
    construct_memory_content_hash,
    normalize_construct_term,
    payload_from_database,
    validate_construct_pair,
)
from .construct_integrity import (
    ConstructIntegrityFinding,
    ConstructIntegrityInspector,
    ConstructIntegrityReport,
)
from .construct_repository import ConstructMemoryRepository
from .eligibility import evaluate_memory_eligibility
from .integrity import (
    MemoryIntegrityFinding,
    MemoryIntegrityInspector,
    MemoryIntegrityReport,
)
from .kernel import MemoryKernel
from .self_episodic_contracts import (
    B87_S1_ACTIVE_MATURITY_STAGES,
    CAPABILITY_OBSERVATION_TYPES,
    CAPABILITY_STABILITIES,
    DEVELOPMENTAL_POLICY_KINDS,
    EVALUATION_ANCHOR_STATES,
    EVALUATION_KINDS,
    FACTUAL_SELF_PAYLOAD_TABLES,
    FACTUAL_SELF_PAYLOAD_TYPES,
    MATURITY_STAGES,
    CapabilityObservationPayload,
    DevelopmentalPolicyVersion,
    EvaluationReferenceAnchor,
    MaturityStatePayload,
    RuntimeIdentityPayload,
    RuntimeSubstrateAttestation,
    TrustedRuntimeAttestor,
    factual_self_content_hash,
    payload_from_database as factual_self_payload_from_database,
    validate_factual_self_pair,
)
from .self_episodic_integrity import (
    SelfEpisodicIntegrityFinding,
    SelfEpisodicIntegrityInspector,
    SelfEpisodicIntegrityReport,
)
from .self_episodic_repository import SelfEpisodicMemoryRepository
from .self_model_projection import PermissionProfileProjection

__all__ = [
    "APPROVAL_TRANSITIONS",
    "B87_S1_ACTIVE_MATURITY_STAGES",
    "CAPABILITY_OBSERVATION_TYPES",
    "CAPABILITY_STABILITIES",
    "CONSTRUCT_PAYLOAD_TABLES",
    "CONSTRUCT_PAYLOAD_TYPES",
    "CONSTRUCT_RELATIONSHIP_POLICIES",
    "DEVELOPMENTAL_POLICY_KINDS",
    "ELIGIBILITY_REASON_ORDER",
    "EVALUATION_ANCHOR_STATES",
    "EVALUATION_KINDS",
    "FACTUAL_SELF_PAYLOAD_TABLES",
    "FACTUAL_SELF_PAYLOAD_TYPES",
    "GOVERNED_RELATIONSHIP_TYPES",
    "LIFECYCLE_TRANSITIONS",
    "MATURITY_STAGES",
    "MEMORY_APPROVAL_AUTHORITY_CLASSES",
    "MEMORY_APPROVAL_OPERATION",
    "MEMORY_DOMAINS",
    "MEMORY_RECORD_TYPES",
    "MEMORY_RELATIONSHIP_OPERATION",
    "NOLAN_INCLUSIVE_AUTHORITY_CLASSES",
    "RELATIONSHIP_TYPES",
    "EligibilityContext",
    "EligibilityDecision",
    "ArchitectureDecisionPayload",
    "CapabilityObservationPayload",
    "ConstructDoctrinePayload",
    "ConstructEntityPayload",
    "ConstructIntegrityFinding",
    "ConstructIntegrityInspector",
    "ConstructIntegrityReport",
    "ConstructMemoryRepository",
    "ConstructRelationshipPayload",
    "DevelopmentalPolicyVersion",
    "EvaluationReferenceAnchor",
    "MemoryApprovalGrant",
    "MemoryIntegrityFinding",
    "MemoryIntegrityInspector",
    "MemoryIntegrityReport",
    "MemoryKernel",
    "MemoryRelationshipGrant",
    "MaturityStatePayload",
    "PermissionProfileProjection",
    "PreferenceRecordPayload",
    "ProjectStatePayload",
    "RecordRelationship",
    "RuntimeIdentityPayload",
    "RuntimeSubstrateAttestation",
    "SelfEpisodicIntegrityFinding",
    "SelfEpisodicIntegrityInspector",
    "SelfEpisodicIntegrityReport",
    "SelfEpisodicMemoryRepository",
    "TerminologyDefinitionPayload",
    "TrustedRuntimeAttestor",
    "approval_authority_classes_for",
    "construct_memory_content_hash",
    "normalize_construct_term",
    "evaluate_memory_eligibility",
    "factual_self_content_hash",
    "factual_self_payload_from_database",
    "memory_domain_for",
    "payload_from_database",
    "validate_approval_transition",
    "validate_lifecycle_transition",
    "validate_construct_pair",
    "validate_factual_self_pair",
]
